### ISSUE TITLE
大佬，跪求简易指导

### ISSUE THREAD

**Issue by shyboy** [LipapaSma/mi-gpt-vue#1]
一直用的无脑docker，请问vue项目怎么部署啊？？

感谢作者~

**Comment by shyboy** [comment]
已经弄好啦，感谢~

**Comment by LipapaSma** [comment]
这个项目用docker也行，页面已经打包好的。除非你要改vue项目

**Comment by LipapaSma** [comment]
这个项目用docker也行，页面已经打包好的。除非你要改vue项目中的页面
